services:
  livekit:
    image: livekit/livekit-server:latest
    command: --dev --config /etc/livekit.yaml
    ports:
      - "7880:7880"
      - "7881:7881"
      - "3478:3478/udp"
      - "3478:3478/tcp"
      - "5349:443/tcp"
      - "30000-35000:30000-35000/udp"
      - "50000-55000:50000-55000/udp"
    deploy:
      resources:
        limits:
          cpus: "8"
          memory: 8G
        reservations:
          cpus: "4"
          memory: 4G
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml:ro
      - ./tls:/etc/livekit-tls:ro
